# Generated by Django 3.1.1 on 2020-09-30 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone_num',
            field=models.TextField(),
        ),
    ]
