# Generated by Django 3.1.1 on 2020-09-30 04:25

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_auto_20200930_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=fernet_fields.fields.EncryptedEmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=fernet_fields.fields.EncryptedCharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone_num',
            field=fernet_fields.fields.EncryptedCharField(max_length=15),
        ),
    ]
