# Generated by Django 3.1.1 on 2020-09-30 05:17

from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_auto_20200930_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='name',
            field=fernet_fields.fields.EncryptedCharField(default='name', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
